name: CI
on: [push]

jobs:
  static_analysis:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: workarea-commerce/ci/bundler-audit@v1
      env:
        GITHUB_ACCESS_TOKEN: ${{ secrets.GITHUB_ACCESS_TOKEN }}
    - uses: workarea-commerce/ci/rubocop@v1
      env:
        GITHUB_ACCESS_TOKEN: ${{ secrets.GITHUB_ACCESS_TOKEN }}

  admin_tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.6.x
    - uses: workarea-commerce/ci/test@v1
      with:
        command: bin/rails app:workarea:test:admin
      env:
        GITHUB_ACCESS_TOKEN: ${{ secrets.GITHUB_ACCESS_TOKEN }}

  core_tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.6.x
    - uses: workarea-commerce/ci/test@v1
      with:
        command: bin/rails app:workarea:test:core
      env:
        GITHUB_ACCESS_TOKEN: ${{ secrets.GITHUB_ACCESS_TOKEN }}

  storefront_tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.6.x
    - uses: workarea-commerce/ci/test@v1
      with:
        command: bin/rails app:workarea:test:storefront
      env:
        GITHUB_ACCESS_TOKEN: ${{ secrets.GITHUB_ACCESS_TOKEN }}

  plugins_tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.6.x
    - uses: workarea-commerce/ci/test@v1
      with:
        command: bin/rails app:workarea:test:plugins
      env:
        GITHUB_ACCESS_TOKEN: ${{ secrets.GITHUB_ACCESS_TOKEN }}
